### ISSUE TITLE
Deeply nested dict raises `SystemError` instead of `RecursionError`

### ISSUE THREAD

**Issue by nineteendo** [nineteendo/jsonyx#11]
```python
>>> import jsonyx as json
>>> obj = {}
>>> for _ in range(100_000):
...     obj = {"": obj}
...
>>> json.dump(obj)
Traceback (most recent call last):
  File "<frozen abc>", line 119, in __instancecheck__
RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wanne\AppData\Local\Programs\Python\Python312\Lib\site-packages\jsonyx\__init__.py", line 614, in dump
    ).dump(obj, fp)
      ^^^^^^^^^^^^^
  File "C:\Users\wanne\AppData\Local\Programs\Python\Python312\Lib\site-packages\jsonyx\__init__.py", line 274, in dump
    fp.write(self._encoder(obj))
             ^^^^^^^^^^^^^^^^^^
SystemError: <built-in method __length_hint__ of dict_keyiterator object at 0x0000023CAC1EF8D0> returned a result with an exception set
```

Offending line:

https://github.com/nineteendo/jsonyx/blob/e4bc986ec0792729a2eabd5a75ebca717e11a085/src/jsonyx/_speedups.c#L1453

**Comment by nineteendo** [comment]
This should be fixed by Python.
